<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libraries">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="library" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="location" type="xs:string" />
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="description" type="xs:string" minOccurs="0" />
                            <xs:element name="version" type="xs:string" />
                            <xs:element name="license" type="xs:string" />
                            <xs:element name="licenseversion" type="xs:string" minOccurs="0" />
                            <xs:element name="repository" type="xs:anyURI" minOccurs="0" />
                            <xs:element name="copyrights" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="copyright" type="xs:string" minOccurs="0"
                                            maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="customised" minOccurs="0">
                                <xs:complexType />
                            </xs:element>
                            <xs:element name="upgradable" type="xs:boolean" minOccurs="0" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>